name: timeshap
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - shap>=0.45
  - matplotlib>=3.10.0
  - ipython>=8.30.0
  - numpy >=1.24
  - pandas>=2.1
  - scikit-learn>=1.2.0
  - scikit-survival>=0.22